# Generated by Django 3.2.6 on 2021-08-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_alter_listing_id_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='id_listing',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
