# Generated by Django 3.2.6 on 2021-08-04 00:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('id_chore', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('start', 'Start'), ('progress', 'Progress'), ('finished', 'Finished')], default='start', max_length=20)),
            ],
        ),
    ]
