# Generated by Django 3.2.6 on 2021-08-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore',
            name='id_chore',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
